title: Finn's Website
# author: Finn B
email: hawkish.dealing.02@icloud.com
description: Welcome to my personal website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://finnb.xyz" # the base hostname & protocol for your site, e.g. http://example.com

remote_theme: riggraz/no-style-please

plugins:
  - jekyll-feed
  - jekyll-seo-tag

theme_config:
  appearance: "light"
  date_format: "%Y-%m-%d"
  show_description: true